### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by sockdrawermoney** [tricitiesvote/tricitiesvote.com#177]
some errors...

```
⠋ extract queries from components
/Users/adam/dev/tricitiesvote.com/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Unable to update lock within the stale threshold
    at /Users/adam/dev/tricitiesvote.com/node_modules/proper-lockfile/lib/lockfile.js:136:25
    at callback (/Users/adam/dev/tricitiesvote.com/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:209:5) {
  code: 'ECOMPROMISED'
}

⠙ extract queries from components
success extract queries from components - 0.393s
warn The GraphQL query in the non-page component "/Users/adam/dev/tricitiesvote.com/src/templates/GuidePage.js" will not be
run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — https://graphql.org/learn/queries/#fragments

/Users/adam/dev/tricitiesvote.com/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:865:20)
    at process.target.send (node:internal/child_process:738:19)
    at /Users/adam/dev/tricitiesvote.com/node_modules/gatsby-cli/lib/reporter/loggers/ipc/index.js:58:13
    at dispatch (/Users/adam/dev/tricitiesvote.com/node_modules/gatsby-cli/lib/reporter/redux/index.js:57:5)
    at /Users/adam/dev/tricitiesvote.com/node_modules/gatsby-cli/lib/reporter/redux/index.js:33:28
    at Array.forEach (<anonymous>)
    at dispatch (/Users/adam/dev/tricitiesvote.com/node_modules/gatsby-cli/lib/reporter/redux/index.js:33:12)
    at Object.endActivity (/Users/adam/dev/tricitiesvote.com/node_modules/redux/lib/redux.js:586:12)
    at Object.end (/Users/adam/dev/tricitiesvote.com/node_modules/gatsby-cli/lib/reporter/reporter-timer.js:54:23)
    at compile (/Users/adam/dev/tricitiesvote.com/node_modules/gatsby/src/query/query-compiler.js:96:12)
    at updateStateAndRunQueries (/Users/adam/dev/tricitiesvote.com/node_modules/gatsby/src/query/query-watcher.ts:223:40)
    at extractQueries (/Users/adam/dev/tricitiesvote.com/node_modules/gatsby/src/services/extract-queries.ts:18:3)
Emitted 'error' event on process instance at:
 {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v18.16.0
```

**Comment by natevw** [comment]
I wonder if you need to `npx gatsby clean` your local repo if you haven't already? I still haven't seen these myself browsing the main site or now clicking through the admin interface either — are there any particular steps needed to reproduce these?
